### ISSUE TITLE
Issue: Module not found: Error: Can't resolve 'jsbn'

### ISSUE THREAD

**Issue by linonetwo** [Authing/authing-js-sdk#118]
- **Version**:

"authing-js-sdk": "4.23.35",

└─┬ authing-js-sdk@4.23.35
  └─┬ sm-crypto@0.3.7
    └── jsbn@1.1.0

- **Platform**:

MacOS

#### Description:

Module not found: Error: Can't resolve 'jsbn' in '/Users/linonetwo/xxx/TiddlyGit-Desktop/node_modules/authing-js-sdk/build/module/lib/sm-crypto/sm2'

```
ERROR in ./node_modules/authing-js-sdk/build/module/lib/sm-crypto/sm2/index.js 6:0-34
Module not found: Error: Can't resolve 'jsbn' in '/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/node_modules/authing-js-sdk/build/module/lib/sm-crypto/sm2'
 @ ./node_modules/authing-js-sdk/build/module/lib/utils.js 39:0-50 48:38-47
 @ ./node_modules/authing-js-sdk/build/module/lib/management/ManagementClient.js 53:0-35 67:21-28
 @ ./node_modules/authing-js-sdk/build/module/index.js 1:0-50 1:0-50
 @ ./src/components/TokenForm/gitTokenHooks.ts 3:0-54 6:38-58
```

在今天升级依赖时遇到这个问题。可能是因为你们依赖 jsbn 的库升级了。

#### Steps to reproduce the error:

![截屏2022-09-25 02 50 39](https://user-images.githubusercontent.com/3746270/192114080-3c3b558c-9f2d-4905-ab32-e0c1b02286d5.png)

**Comment by zhaoyiming0803** [comment]
你好，可以贴一下相关的使用代码吗？这边复现排查下。

**Comment by linonetwo** [comment]
你好，是这个应用里的 [https://github.com/tiddly-gittly/TidGi-Desktop/search?q=authing-js-sdk](https://github.com/tiddly-gittly/TidGi-Desktop/search?q=authing-js-sdk)

我降级后问题消失。你若想复现可以 clone 下来， packagejson 里改为最新版，然后 npm i ，然后 npm run start ，在命令行里就能看到报错了。
