### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by pash90** [Authing/authing-js-sdk#28]
我在将Web SDK集成到我的应用程序中，遇到了一个问题。 我能正确注册、登录、注销，但我在验证用户邮箱的时候一直遇到问题。 我在Authing控制台已经设置好为电子邮件的模板。
当我收到来自Authing的电子邮件时，每次点击所提供的链接后验证都失败，然后都会收到以下的信息：

```
验证失败，获取邮件模板失败, 页面将在5秒后关闭…
```

**Comment by leinue** [comment]
好滴，我们排查一下

**Comment by leinue** [comment]
我们已经修正这个问题啦，感谢提出，这是一个因为权限出问题导致的 BUG。

The BUG you proposed in Github about mail validation has been fixed. Thank you for putting forward this issue. If you have any questions, please contact us again.

My email: xieyang#authing.cn

**Comment by pash90** [comment]
谢谢
