### ISSUE TITLE
undefined when sendSmsCode

### ISSUE THREAD

**Issue by qianfeiqianlan** [Authing/authing-js-sdk#65]
https://github.com/Authing/authing.js/blob/431ae4e88ef583f022ea1316c1e3a6bd22db075b/src/lib/common/HttpClient.ts#L46

在调用发送短信的时候，这里的data的值是`{
    code: 200, 
    message: '发送成功'
  }`， 返回的是**data.data**，得到一个undefined

**Comment by qianfeiqianlan** [comment]
@liaochangjiang

**Comment by liaochangjiang** [comment]
@qianfeiqianlan 这个接口应该是不需要返回值的，HttpClient 对 code 不为 200 的 response 做了统一的异常处理：https://github.com/Authing/authing.js/blob/master/src/lib/common/HttpClient.ts#L44

**Comment by qianfeiqianlan** [comment]
@liaochangjiang 我参考了这个文档 [使用手机验证码登录](https://docs.authing.cn/sdk/sdk-for-javascript/#%E4%BD%BF%E7%94%A8%E6%89%8B%E6%9C%BA%E9%AA%8C%E8%AF%81%E7%A0%81%E7%99%BB%E5%BD%95)，但是当我调用SDK发送短信验证码的时候，得到的返回值是undefined，跟踪代码到了issue链接的那个地方，看到data的值是对的，但返回的是data.data
目前我这边的issue表现就是，调用了sendSmsCode，但是返回值为undefined，并没又得到 `{ code: 200, message: '发送成功' }`

**Comment by liaochangjiang** [comment]
@qianfeiqianlan 你给的这个文档是老版本 SDK 的（顺便好奇一下你是在哪找到这个文档的入口的呢），最新的文档在 [发送短信验证码](https://docs.authing.cn/sdk/sdk-for-node/authentication/AuthenticationClient.html#%E5%8F%91%E9%80%81%E7%9F%AD%E4%BF%A1%E9%AA%8C%E8%AF%81%E7%A0%81) 。

新版 SDK 的异常处理方式做了更新，对于 `code` 不为 `200` 的请求做了抛错处理，开发者可以通过 `try/catch` 来判断操作是否成功，详情请见 [错误处理方式](https://docs.authing.cn/sdk/sdk-for-node/#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86) 。

**Comment by qianfeiqianlan** [comment]
@liaochangjiang  好的好的，我就是从官网找到的，然后用起来发现不太对劲🤣

**Comment by liaochangjiang** [comment]
@qianfeiqianlan 好的 🤣 我们更新下官网的文档链接
