### ISSUE TITLE
Identities 未返回

### ISSUE THREAD

**Issue by linonetwo** [Authing/authing-js-sdk#74]
https://github.com/Authing/authing.js/blob/354968962ad217289c39b6a699adaee090254937/src/types/graphql.v2.ts#L545

这个要改哪里，改 https://github.com/Authing/authing.js/blob/master/src/lib/authentication/AuthenticationClient.ts 吗

---

看样子应该是要加在 https://github.com/Authing/authing.js/blob/354968962ad217289c39b6a699adaee090254937/src/lib/authentication/SocialAuthenticationClient.ts#L32 里，这里的 https://github.com/Authing/authing.js/blob/354968962ad217289c39b6a699adaee090254937/src/lib/authentication/SocialAuthenticationClient.ts#L144 里没有 identities ，需要再 await 一次 graphql 请求来获取 identities

**Comment by zhaoyiming0803** [comment]
下载最新版本看下
