### ISSUE TITLE
navigator问题建议

### ISSUE THREAD

**Issue by GuoBinyong** [Authing/authing-js-sdk#77]
[提交]: https://github.com/Authing/authing.js/commit/64456235b563530cad48dd1c6f1f9ab016804932

这个[提交][] 中的如下代码是有问题的：

<img width="581" alt="错误的兼容处理" src="https://user-images.githubusercontent.com/19264309/119599960-99936b80-be18-11eb-9d97-647e5091fadb.png">

<img width="937" alt="访问兼容API" src="https://user-images.githubusercontent.com/19264309/119599981-a1531000-be18-11eb-85fd-e2895686af78.png">

可选运算符 `navigator?.userAgent`  可用的前提是 `navigator ` 变量已经被定义了，如果  `navigator ` 没定义，执行这行代码时仍然会 ReferenceError 错误，因为可先运算符的 等效 js 代码是 `navigator === null || navigator === void 0 ? void 0 : navigator.userAgent`

对于这种兼容 node、Web、worker 环境的代码的正确处理方式应是：
1. 安装 `conf-global` 包（该包非常小，零依赖，不会增加项目负担） `npm i conf-global`
2. 在应用入口文件最前面添加 `import "conf-global"`
3. 凡是访问全局性有兼容的API 都改成通过 `globalThis` 全局对象访问的方式，如： `globalThis. navigator?. userAgent`

**Comment by shangsinian** [comment]
@GuoBinyong 感谢提这个建议，方便发个 PR 么～

**Comment by GuoBinyong** [comment]
嗯，好的，晚些时候发

**Comment by shangsinian** [comment]
@GuoBinyong 感谢～
